Add option to disable ice mismatch check.
pjsip/pjproject pull request #2538
Opened 2020-10-02 07:43 UTC by trengginas

RFC [5245 ](https://tools.ietf.org/html/rfc5245#section-5.1) states that:
> The agent will proceed with the ICE procedures defined in this
   specification if, for each media stream in the SDP it received, the
   default destination for each component of that media stream appears
   in a candidate attribute.  For example, in the case of RTP, the IP
   address and port in the c and m lines, respectively, appear in a
   candidate attribute and the value in the rtcp attribute appears in a
   candidate attribute.

If the IP address and port in c and m lines doesn't appears in the candidate attribute, 
then ice-mismatch attribute will be returned.

The updated RFC [8455](https://tools.ietf.org/html/rfc8445#section-5.4) states that:
> Certain middleboxes, such as ALGs, can alter signaling information in
   ways that break ICE (e.g., by rewriting IP addresses in SDP).  This
   is referred to as "ICE mismatch".  If the using protocol is
   vulnerable to ICE mismatch, the responding agent needs to be able to
   detect it and inform the peer ICE agent about the ICE mismatch.

In some scenario, the IP address and port check is not required and might break ICE.

This ticket will allow to disable the check so that the ICE can continue.

2020-10-02 10:49 UTC, nanangizz requested changes
also the patch seems to fail in the sipp tests, please check.

2020-10-02 10:49 UTC, nanangizz commented on pjmedia/include/pjmedia/transport_ice.h
> +     * is required on some scenario.
The rfc5245 seems to have identified the ALG issues as well:
> Unfortunately, many ALGs are known to work poorly in these corner
>    cases.  ICE does not try to work around broken ALGs, as this is
>    outside the scope of its functionality.  ICE can help diagnose these
>    conditions, which often show up as a mismatch between the set of
>    candidates and the m and c lines and rtcp attributes.  The ice-
>    mismatch attribute is used for this purpose.

And rfc8445 does not seems to cancel ice-mismatch rule.

So I think the docs needs to be updated.

2020-10-05 03:07 UTC, nanangizz approved these changes
just a minor/optional note.

2020-10-05 03:07 UTC, nanangizz commented on pjmedia/src/pjmedia/transport_ice.c
> +                (!disable_ice_mismatch &&
perhaps a bit optimization, by removing `!disable_ice_mismatch` condition?

2020-10-05 03:07 UTC, nanangizz commented on pjmedia/src/pjmedia/transport_ice.c
> +                (!disable_ice_mismatch &&
same as above

2020-10-08 04:59 UTC, trengginas commented on pjmedia/src/pjmedia/transport_ice.c
> +                (!disable_ice_mismatch &&
done

2020-10-08 04:59 UTC, trengginas commented on pjmedia/src/pjmedia/transport_ice.c
> +                (!disable_ice_mismatch &&
done

2020-10-08 06:36 UTC, sauwming approved these changes

2020-10-12 05:38 UTC, merged