Fixed remote address change checking in DTLS transport
pjsip/pjproject pull request #2703
Opened 2021-04-22 11:14 UTC by sauwming

Currently the remote address change check in DTLS transport doesn't take into account rtcp multiplexing. Therefore, it will incorrectly think that the remote rtcp address has changed and try to renegotiate DTLS key.

This can cause no media when both DTLS and rtcp multiplexing are enabled due to DTLS key negotiation never completed. One can know this from the log which will output:
```Error sending RTP: SRTP parameters negotiation still in progress (PJMEDIA_SRTP_EKEYNOTREADY)```
even after some time has passed.

2021-04-22 12:18 UTC, ismangil requested changes
The DTLS debug flag defaults to 1 in this code. It needs to be kept at 0.

2021-04-23 02:40 UTC, nanangizz commented on pjmedia/src/pjmedia/transport_srtp_dtls.c
> +	}
What if remote SDP has both attributes, rtcp-mux & rtcp? Shouldn't it check for rtcp-mux first?

2021-04-23 03:48 UTC, nanangizz approved these changes

2021-04-23 04:34 UTC, trengginas approved these changes

2021-04-23 05:24 UTC, merged