Don't call SSL_shutdown() when receiving SSL_ERROR_SYSCALL or SSL_ERROR_SSL
pjsip/pjproject pull request #3577
Opened 2023-05-24 03:53 UTC by trengginas

This is to fix #3576.
Before calling `SSL_shutdown()`, a check to SSL_ERROR_SYSCALL and SSL_ERROR_SSL is required.

2023-05-24 04:50 UTC, sauwming commented on pjlib/src/pj/ssl_sock_ossl.c
> +    ossl_sock_t* ossock = (ossl_sock_t*)ssock;
Minor: our PointerAlignment is actually `Right`, i.e. see the initial code:
`ossl_sock_t *ossock = (ossl_sock_t *)ssock`

2023-05-24 04:50 UTC, sauwming commented on pjlib/src/pj/ssl_sock_ossl.c
> +     * Don't send notify when the last error is SSL_ERROR_SYSCALL or SSL_ERROR_SSL.
Replace `send notify` with `call SSL_shutdown()`.

Yes, SSL_shutdown() will send notify, but it's only one of the steps.
`Note that SSL_shutdown() must not be called if a previous fatal error has occurred on a connection i.e. if SSL_get_error() has returned SSL_ERROR_SYSCALL or SSL_ERROR_SSL.

The shutdown procedure consists of two steps: sending of the close_notify shutdown alert, and reception of the peer's close_notify shutdown alert. The order of those two steps depends on the application.`
https://www.openssl.org/docs/manmaster/man3/SSL_shutdown.html

Also change the boolean below.

2023-05-24 19:54 UTC, creslin2877 commented
The only concern I have is that last_err might be set from an ssl_write context while ssl_read is being executed (due to concerns brought up in #3575).  I just pushed my patch up for it, so we'll probably have a merge conflict to deal with whenever your branch or mine goes in, but in any case, I think the locking in the fix for #3575 will make things a bit better.

2023-05-31 05:09 UTC, sauwming commented
Since #3583 has been integrated, you can merge with the latest master to resolve the conflict.

2023-06-01 13:24 UTC, creslin2877 requested changes
As mentioned in my previous comment, we need to cover the case where we get an SSL_ERROR_SSL from the SSL_read() function too.

2023-06-05 04:11 UTC, sauwming commented
> As mentioned in my previous comment, we need to cover the case where we get an SSL_ERROR_SSL from the SSL_read() function too.

Since, after merging, it now already uses the locking in `ssl_read()`, let us know if there are further modifications required.

2023-06-26 06:31 UTC, sauwming commented
@creslin2877, let us know if there's any issue with the latest patch, so we can merge it for 2.13.1.

2023-06-27 08:40 UTC, sauwming commented
I just realised that the addition of `ssl_reset_sock_state_with_error()` will break other SSL backends. Can we avoid modifying the internal API?

2023-06-27 19:51 UTC, creslin2877 commented
I think you've covered the case that triggered my concern.  Thanks!

2023-06-28 01:31 UTC, sauwming approved these changes

2023-07-04 06:59 UTC, nanangizz approved these changes

2023-07-05 03:38 UTC, merged